# See: https://taskfile.dev/api

version: "3"

tasks:
  migrate:
    desc: "Migrate sso database"
    cmds:
      - go run ./cmd/migrator/ --storage-path=./storage/sso.db --migrations-path=./migrations
  testmigrate:
    desc: "Migrate test sso database"
    cmds:
      - go run ./cmd/migrator/ --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test